WebApplication1/Controllers/SucursalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class SucursalesController : Controller
    {
        private FacturacionEntities7 db = new FacturacionEntities7();

        // GET: Sucursales
        public ActionResult Index()
        {
            using (FacturacionEntities7 db = new FacturacionEntities7()) ;
            {
                var text = "";
                if (Request.Form["search"] == null) {
                     text = "";
                    

                }else{
                     text = Request.Form["search"];
                }
                var data = db.Sucursal.Where(s => s.Sucursal1.Contains(text) || s.Sucursal1 == null).OrderBy(s => s.Sucursal1).ToList();
                return View(data);
            }

            
        }

        // GET: Sucursales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sucursal sucursal = db.Sucursal.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            return View(sucursal);
        }

        // GET: Sucursales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sucursales/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDSucursal,Sucursal1")] Sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                db.Sucursal.Add(sucursal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sucursal);
        }

        // GET: Sucursales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sucursal sucursal = db.Sucursal.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            return View(sucursal);
        }

        // POST: Sucursales/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDSucursal,Sucursal1")] Sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(sucursal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sucursal);
        }

        // GET: Sucursales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sucursal sucursal = db.Sucursal.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            return View(sucursal);
        }

        // POST: Sucursales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sucursal sucursal = db.Sucursal.Find(id);
            db.Sucursal.Remove(sucursal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Sucursales/Create.cshtml
@model WebApplication1.Models.Sucursal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-title">
            <h4>Crear Sucursal</h4>
        </div>
        <hr />
        <div class="card-content">
            @Html.DisplayName("Sucursal")

          
            <div class="form-group">
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Sucursal1, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.Sucursal1, "", new { @class = "text-danger" })
                </div>


              
                
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
   

WebApplication1/Views/Sucursales/Delete.cshtml
@model WebApplication1.Models.Sucursal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sucursal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sucursal1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sucursal1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Sucursales/Details.cshtml
@model WebApplication1.Models.Sucursal

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Sucursal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sucursal1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sucursal1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDSucursal }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Sucursales/Edit.cshtml
@model WebApplication1.Models.Sucursal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sucursal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDSucursal)

        <div class="form-group">
            @Html.LabelFor(model => model.Sucursal1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sucursal1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sucursal1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Sucursales/Index.cshtml
@model IEnumerable<WebApplication1.Models.Sucursal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br/>
<br />
<br />
<div class="card">
    <div class="card-title card-stacked" >
        <h2>Sucursales</h2>
        <p>
            <a class="waves-effect waves-light btn" href='@Url.Action("Create", "Sucursales")'><i class="material-icons left">add</i>Crear Nuevo</a>
        </p>

    </div>
   @using (Html.BeginForm("Index", "Sucursales"))
   {
    <input name="search" type="search" class="form-control input-sm" placeholder="Buscar" aria-controls="example">
    <input type="submit" value="buscar"   class="btn"/>
   }
    <div class="card-content">
        <table id="example" class="table table-striped" cellspacing="0" width="100%">

            <thead>
                <tr>
                    <th>
                        Sucursal
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>

                @{
                    if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sucursal1)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.IDSucursal }) |
                                    @Html.ActionLink("Detalle", "Details", new { id = item.IDSucursal }) |
                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.IDSucursal })
                                </td>
                            </tr>
                        }
                    }
                }



            </tbody>
        </table>
    </div>
</div>